version: '3'
services:
  db:
    image: mysql
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    networks:
      - eldorado-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: el_dorado_challenge_image
    container_name: el_dorado_challenge_service
    restart: always
    ports: 
      - 3000:3000
    environment:
      ENV: prod
      PORT_DB: 3306
      HOST_DB: mysql_db
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    networks:
      - eldorado-network
volumes:
  db:
    driver: local
networks:
  eldorado-network: